### ISSUE TITLE
Support for google-apiclient 1.3.1

### ISSUE THREAD

**Issue by aahamlin** [scotch/engineauth#27]
I just discovered this project yesterday. Working through an example with latest Google appengine and over the last few years it appears that apiclient.oauth has been removed. Is my investigation correct?

The stacktrace I am getting using apiclient 1.3.1 is:

Traceback (most recent call last):
  File "/home/andrew/src/aah-profile-report/engineauth/utils.py", line 29, in import_class
    mod = __import__(path, fromlist=[klass])
  File "/home/andrew/.eclipse/1712548941_linux_gtk_x86_64/plugins/org.python.pydev_4.0.0.201504132356/pysrc/pydev_monkey_qt.py", line 71, in patched_import
  File "/home/andrew/src/aah-profile-report/engineauth/strategies/linkedin.py", line 5, in <module>
    from engineauth.strategies.oauth import OAuthStrategy
  File "/home/andrew/.eclipse/1712548941_linux_gtk_x86_64/plugins/org.python.pydev_4.0.0.201504132356/pysrc/pydev_monkey_qt.py", line 71, in patched_import
  File "/home/andrew/src/aah-profile-report/engineauth/strategies/oauth.py", line 2, in <module>
    from apiclient.oauth import FlowThreeLegged
  File "/home/andrew/.eclipse/1712548941_linux_gtk_x86_64/plugins/org.python.pydev_4.0.0.201504132356/pysrc/pydev_monkey_qt.py", line 71, in patched_import
ImportError: No module named apiclient.oauth
ERROR    2015-06-19 01:19:42,085 cgi.py:122] Traceback (most recent call last):
  File "/home/andrew/src/aah-profile-report/helloworld.py", line 34, in <module>
    main()
  File "/home/andrew/src/aah-profile-report/helloworld.py", line 31, in main
    run_wsgi_app(application)
  File "/home/andrew/google-cloud-sdk/platform/google_appengine/google/appengine/ext/webapp/util.py", line 99, in run_wsgi_app
    run_bare_wsgi_app(add_wsgi_middleware(application))
  File "/home/andrew/google-cloud-sdk/platform/google_appengine/google/appengine/ext/webapp/util.py", line 117, in run_bare_wsgi_app
    result = application(env, _start_response)
  File "/home/andrew/src/aah-profile-report/engineauth/middleware.py", line 144, in __call__
    strategy_class = self._load_strategy(provider)
  File "/home/andrew/src/aah-profile-report/engineauth/middleware.py", line 164, in _load_strategy
    "'provider.{0}' config dict".format(provider))
Exception

INFO     2015-06-19 01:19:42,142 module.py:790] default: "GET /auth/linkedin HTTP/1.1" 500 -

Notice the import error
ImportError: No module named apiclient.oauth

The current apiclient documentation (and library) make not mention of this package.
https://developers.google.com/api-client-library/python/guide/google_app_engine

Just wondering, if an update to engineauth in the works to support these changes or have I misunderstood something in my research?

**Comment by kylefinley** [comment]
Hey @aahamlin, 

I believe the API has changed. This project is definitely in need of an update.

If you haven't already you might try [SimpleAuth](https://github.com/crhym3/simpleauth). I believe it uses the current version.
